config/routes.rb
Rails.application.routes.draw do
  resources :people

  get 'welcome/index'

  resources :life_events

  resources :schools

  root 'welcome#index'

end

app/models/life_event.rb
class LifeEvent < ActiveRecord::Base
  belongs_to :person

  validates :person_id, presence: true
  validates :title, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
  validates :description, length: { maximum: 140 }
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :life_event, dependent: :destroy
  has_many :school, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  def name_joined
    "#{first_name} #{last_name}"
  end
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :person

  validates :person_id, presence: true
  validates :name, presence: true
  validates :beginning_year, presence: true, numericality: { less_than_or_equal_to: :ending_year }
  validates :ending_year, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/life_events_controller.rb
class LifeEventsController < ApplicationController
  before_action :set_life_event, only: [:show, :edit, :update, :destroy]

  # GET /life_events
  # GET /life_events.json
  def index
    @life_events = LifeEvent.all
  end

  # GET /life_events/1
  # GET /life_events/1.json
  def show
  end

  # GET /life_events/new
  def new
    @life_event = LifeEvent.new
  end

  # GET /life_events/1/edit
  def edit
  end

  # POST /life_events
  # POST /life_events.json
  def create
    @life_event = LifeEvent.new(life_event_params)

    respond_to do |format|
      if @life_event.save
        format.html { redirect_to @life_event, notice: 'Life event was successfully created.' }
        format.json { render :show, status: :created, location: @life_event }
      else
        format.html { render :new }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /life_events/1
  # PATCH/PUT /life_events/1.json
  def update
    respond_to do |format|
      if @life_event.update(life_event_params)
        format.html { redirect_to @life_event, notice: 'Life event was successfully updated.' }
        format.json { render :show, status: :ok, location: @life_event }
      else
        format.html { render :edit }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /life_events/1
  # DELETE /life_events/1.json
  def destroy
    @life_event.destroy
    respond_to do |format|
      format.html { redirect_to life_events_url, notice: 'Life event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_life_event
      @life_event = LifeEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def life_event_params
      params.require(:life_event).permit(:person_id, :title, :year, :description)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:id, :first_name, :last_name, :schools, :life_events)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:person_id, :name, :beginning_year, :ending_year)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @last_user = Person.all.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/life_events_helper.rb
module LifeEventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">

        <li class="name">
          <h1>
            <a href="#">
              Life Tracker
            </a>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
      </ul>

      <section class="top-bar-section">

        <ul class="right">
          <li class="divider"></li>
          <li class="events"><%= link_to "Home", "/" %></li>
          <li class="divider"></li>
          <li class="events"><%= link_to "Schools Attended", schools_path %></li>
          <li class="divider"></li>
          <li class="events"><%= link_to "Life Events", life_events_path %></li>
          <li class="divider"></li>
          <li class="events"><%= link_to "Users", people_path %></li>
          <li class="divider"></li>
        </ul>
      </section>
    </nav>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/life_events/_form.html.erb
<%= form_for(@life_event) do |f| %>
  <% if @life_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@life_event.errors.count, "error") %> prohibited this life_event from being saved:</h2>

      <ul>
      <% @life_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :person_id, "Name", class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.collection_select :person_id, Person.all, :id, :name_joined %></div>
  </div>
  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :title, class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.text_field :title %></div>
  </div>
  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :year, class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.text_field :year %></div>
  </div>
  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :description, class: "left inline" %></div>
    <div class="small-10 columns left hug-left"><%= f.text_field :description %></div>
  </div>
  <div class="row">
    <div class="small-9 columns hug-left"><%= f.submit %></div>
  </div>
<% end %>

app/views/life_events/edit.html.erb
<h1>Editing life_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @life_event %> |
<%= link_to 'Back', life_events_path %>

app/views/life_events/index.html.erb
<h1>Listing life_events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Year</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @life_events.each do |life_event| %>
      <tr>
        <td><%= life_event.person.name_joined %></td>
        <td><%= life_event.title %></td>
        <td><%= life_event.year %></td>
        <td><%= life_event.description %></td>
        <td><%= link_to 'Show', life_event %></td>
        <td><%= link_to 'Edit', edit_life_event_path(life_event) %></td>
        <td><%= link_to 'Destroy', life_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Life event', new_life_event_path %>

app/views/life_events/new.html.erb
<h1>Record a Life Event</h1>

<%= render 'form' %>

app/views/life_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @life_event.person.name_joined %>
</p>

<p>
  <strong>Title:</strong>
  <%= @life_event.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @life_event.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @life_event.description %>
</p>

<%= link_to 'Edit', edit_life_event_path(@life_event) %> |
<%= link_to 'Back', life_events_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :first_name, class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.text_field :first_name %></div>
  </div>
  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :last_name, class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.text_field :last_name %></div>
  </div>
  <div class="row">
    <div class="small-9 columns hug-left"><%= f.submit %></div>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>Enter Your Name</h1>

<%= render 'form' %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p class="spacing-top spacing-left">
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p class="spacing-left">
  <strong>Last name:</strong>
  <%= @person.last_name %><br><br>
</p>

<p class="spacing-top spacing-left"><strong>Schools Attended</strong></p>

<% name = "" %>
<% beginning_year = 0 %>
<% ending_year = 0 %>
<% @person.school.order(:beginning_year).each do |school| %>
<% name = school.name %>
<% beginning_year = school.beginning_year %>
<% ending_year = school.ending_year %>
<p class="spacing-left">
  <strong>School:</strong>
  <%= name %> &nbsp; | &nbsp;
  <strong>Year Started:</strong>
  <%= beginning_year %> &nbsp; | &nbsp;
  <strong>Year Graduated:</strong>
  <%= ending_year %>
</p>
<% end %>

<p class="spacing-top spacing-left"><strong>Life Events</strong></p>

<% title = "" %>
<% year = 0 %>
<% description = "" %>
<% @person.life_event.order(:year).each do |event| %>
<% title = event.title %>
<% year = event.year %>
<% description = event.description %>
<p class="spacing-left">
  <strong>Title:</strong>
  <%= title %> &nbsp; | &nbsp;
  <strong>Year:</strong>
  <%= year %> &nbsp; | &nbsp;
  <strong>Description:</strong>
  <%= description %>
</p>
<% end %>

<p class="spacing-top spacing-left">
  <%= link_to 'Edit', edit_person_path(@person) %> |
  <%= link_to 'Back', people_path %>
</p>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :person_id, "Name", class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.collection_select :person_id, Person.all, :id, :name_joined %></div>
  </div>
  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :name, "School", class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.text_field :name %></div>
  </div>
  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :beginning_year, "Year Started", class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.text_field :beginning_year %></div>
  </div>
  <div class="row hug-left">
    <div class="small-2 columns"><%= f.label :ending_year, "Year Graduated", class: "left inline" %></div>
    <div class="small-4 columns left hug-left"><%= f.text_field :ending_year %></div>
  </div>
  <div class="row">
    <div class="small-9 columns hug-left"><%= f.submit %></div>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>School</th>
      <th>Beginning year</th>
      <th>Ending year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.person.name_joined %></td>
        <td><%= school.name %></td>
        <td><%= school.beginning_year %></td>
        <td><%= school.ending_year %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>Enter Your Schooling</h1>

<%= render 'form' %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.person.name_joined %>
</p>

<p>
  <strong>School:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Beginning year:</strong>
  <%= @school.beginning_year %>
</p>

<p>
  <strong>Ending year:</strong>
  <%= @school.ending_year %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/welcome/index.html.erb
 <body>
   <h1>Life Tracker</h1>

  <p class="spacing-top spacing-left">
    <strong>Newest User:</strong>
    <%= @last_user.name_joined %>
  </p>

  <p class="spacing-top spacing-left"><strong>Last School Attended</strong></p>

  <% name = "" %>
  <% beginning_year = 0 %>
  <% ending_year = 0 %>
  <% @last_user.school.order(:beginning_year).each do |school| %>
    <% if school.beginning_year > beginning_year %>
    <% name = school.name %>
    <% beginning_year = school.beginning_year %>
    <% ending_year = school.ending_year %>
    <% end %>
  <% end %>
  <p class="spacing-left">
    <strong>Name:</strong>
    <%= name %> &nbsp; | &nbsp;
    <strong>Year Started:</strong>
    <%= beginning_year %> &nbsp; | &nbsp;
    <strong>Year Graduated:</strong>
    <%= ending_year %>
  </p>

  <p class="spacing-top spacing-left"><strong>Most Recent Life Event</strong></p>

  <% title = "" %>
  <% year = 0 %>
  <% description = "" %>
  <% @last_user.life_event.order(:year).each do |event| %>
    <% if event.year > year %>
    <% title = event.title %>
    <% year = event.year %>
    <% description = event.description %>
    <% end %>
  <% end %>
  <p class="spacing-left">
    <strong>Title:</strong>
    <%= title %> &nbsp; | &nbsp;
    <strong>Year:</strong>
    <%= year %> &nbsp; | &nbsp;
    <strong>Description:</strong>
    <%= description %>
  </p>

</body>